options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # - name: "ubuntu"
  #   entrypoint: "bash"
  #   args:
  #     - "-c"
  #     - "cat package.json && echo 'Package.json content printed above.'"
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: "bash"
    args: ["-c", "rm -rf node_modules package-lock.json || true"]

  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "--force"]

  - name: "gcr.io/cloud-builders/npm"
    env:
      - "NODE_OPTIONS=--max-old-space-size=4096"
    args: ["run", "build"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gsutil"
    args: ["-m", "cp", "-r", "build/*", "gs://shopinggo/"]
